### PR TITLE
WIP - Initial Functionality

### PR DESCRIPTION
**Pull request by ahwillia**
This is a work in progress, do not merge yet.

Things needed before merge:

- [x] Tests
- [x] A working example in `tests/`

@erichson - please comment on general organization of the code. I am proposing three core objects for the library: `Ktensor`, `FitResult` and `Ensemble`. Do they all make sense to you?

### CODE REVIEW

**Comment by erichson** [comment]
This looks pretty good to me. Just minor comments:

* I would suggest that we have only the option compression={True, False} and then the compression_method={'deterministic', 'randomized', 'sketched'}. In addition we need then some good default tuning parameters for the compression_method, i.e, oversampling $p$ and for the randomized method we need the option for additional power iterations $q$. 

* For the class FitResult we should be consistent with naming variables, i.e., X -> tensors and U -> factors.

* Efficient fit criterion are needed, indeed.

**Comment by ahwillia** [comment]
@erichson - just pushed a working prototype with `cp_als` now working. I added a lightweight dependency to this package -- https://github.com/bmc/munkres -- which solves how to permute/align the factors across multiple runs to make sure we get the same result.

I am probably not going to touch the code much until late next week. Would love to see you push it a bit further before then - and we can chat sometime around next Friday maybe.

**Comment by ahwillia** [comment]
@erichson - one more thing. We can either start to merge this into 0.1 or keep working on this PR here. Totally up to you.

**Comment by erichson** [comment]
Great job.

**Pull request merged**
